# Generated by Django 4.2.8 on 2023-12-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['create_date'], 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
